'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,LockKeyhole,Pause,Play,ScanLine,RotateCcw} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {HeroScene} from './hero';
import {Mark} from './shared';
import {CHAMBER_DURATION} from './chamber-motion';
const choices=[{id:'goal',title:'Project goal',text:'Explain a complex idea simply.'},{id:'tone',title:'Writing preference',text:'Use concise, plain language.'}];
export function BoundaryHero({forcePaused=false}:{forcePaused?:boolean}){
 const[selected,setSelected]=useState(['goal']);const[stage,setStage]=useState<'idle'|'scanning'|'ready'>('idle');const[paused,setPaused]=useState(false);const[turn,setTurn]=useState(0);const[startedAt,setStartedAt]=useState(0);const[phase,setPhase]=useState(0);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);
 const cancel=()=>{timers.current.forEach(clearTimeout);timers.current=[]};
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setPaused(m.matches);if(m.matches){cancel();setStage(current=>current==='scanning'?'ready':current);setPhase(3)}};update();m.addEventListener('change',update);return()=>{m.removeEventListener('change',update);cancel()}},[]);
 useEffect(()=>{if(forcePaused){cancel();setPaused(true);setStage(current=>current==='scanning'?'ready':current);setPhase(3)}else setPaused(matchMedia('(prefers-reduced-motion: reduce)').matches)},[forcePaused]);
 const change=(id:string,include:boolean)=>{cancel();setStage('idle');setPhase(0);setSelected(list=>include?[...list.filter(x=>x!==id),id]:list.filter(x=>x!==id))};
 const preview=()=>{cancel();setStartedAt(performance.now());setPhase(0);if(paused){setStage('ready');setPhase(3);return}setStage('scanning');[800,1700,3400].forEach((ms,i)=>timers.current.push(setTimeout(()=>setPhase(i+1),ms)));timers.current.push(setTimeout(()=>setStage('ready'),CHAMBER_DURATION))};
 const toggleMotion=()=>{if(forcePaused)return;if(!paused&&stage==='scanning'){cancel();setStage('ready');setPhase(3)}setPaused(!paused)};
 const status=stage==='idle'?'Your context waits for your choice.':stage==='ready'?'Your request. Only what you selected.':['Gathering the context','Opening the selected passage','Selected context crosses. The email stays out.','Assembling your request'][phase];
 return <section className={'boundary-hero '+(paused?'motion-paused ':'')+'state-'+stage+' chamber-phase-'+phase} aria-labelledby="boundary-heading">
 <div className="boundary-kicker"><span>ANONYX / PRIVACY-AWARE AI</span><span>YOUR CONTEXT. YOUR CALL.</span></div>
 <div className="boundary-heading"><h1 id="boundary-heading">Your life<br/><em>isn’t a prompt.</em></h1><div className="boundary-intro"><p>Give AI the right context.<br/>Keep the rest of your world<br className="desktop"/> to yourself.</p><div className="boundary-actions"><a href="/workspace" className="button primary hero-workspace-cta"><span className="hero-cta-symbol" aria-hidden="true"><Mark/></span><span>Open workspace</span></a><a href="/privacy" className="boundary-text-link">How privacy works</a></div></div></div>
 <div className="boundary-lab">
 <section className="boundary-input" aria-labelledby="input-heading"><div className="lane-heading"><span>01 / YOUR SIDE</span><LockKeyhole size={14}/></div><h2 id="input-heading">Choose what crosses.</h2><div className="private-strip"><span>alex@example.com</span><span><LockKeyhole size={11}/> STAYS HERE</span></div><div className="boundary-options">{choices.map(c=><label key={c.id} className={'boundary-choice '+(selected.includes(c.id)?'included':'')}><Checkbox aria-label={'Include '+c.title.toLowerCase()} checked={selected.includes(c.id)} onCheckedChange={v=>change(c.id,v===true)}/><span><strong>{c.title}</strong><small>{c.text}</small></span><span className="choice-state">{selected.includes(c.id)?'IN':'OUT'}</span></label>)}</div><button className="boundary-run" onClick={preview} disabled={stage==='scanning'}><ScanLine size={16}/>{stage==='scanning'?'Passing the boundary…':stage==='ready'?'Replay the passage':'Preview selected request'}</button></section>
 <div className="boundary-chamber"><div className="chamber-label"><span>02</span> DISCLOSURE CHAMBER</div><div className="chamber-sequence" aria-hidden="true">{['Gather','Select','Pass','Assemble'].map((label,i)=><span key={label} className={(stage==='ready'||stage==='scanning'&&phase>=i)?'lit':''}><i/>{label}</span>)}</div><div className="gate-scene"><HeroScene stage={stage} startedAt={startedAt} selected={[selected.includes('goal'),selected.includes('tone')]} paused={paused} rotation={turn}/></div><div className="chamber-baseline"><span className="chamber-status" role="status">{status}</span><div><button onClick={toggleMotion} disabled={forcePaused} aria-label={paused?'Play hero animation':'Pause hero animation'}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button onClick={()=>setTurn(v=>v+Math.PI/4)} aria-label="Rotate disclosure chamber"><RotateCcw size={16}/></button></div></div></div>
 <section className="boundary-output" aria-labelledby="output-heading"><div className="lane-heading"><span>03 / MODEL SIDE</span><span className="output-count">{stage==='ready'?selected.length:'—'} CONTEXT</span></div><h2 id="output-heading">Only the essentials.</h2><div className="request-receipt" aria-live="polite">{stage==='idle'?<><span className="receipt-caption">WAITING FOR YOUR REVIEW</span><p>Only what you select.</p><span className="receipt-empty">Ready when you are.</span></>:stage==='scanning'?<><span className="receipt-caption">REVIEWING THE PASSAGE</span><div className="scan-lines" aria-hidden="true"><i/><i/><i/></div><p>The example email stays out of this request.</p></>:<><span className="receipt-caption"><Check size={13}/> REQUEST PREVIEW</span><p className="receipt-prompt">“Help me shape this idea.”</p>{choices.filter(c=>selected.includes(c.id)).map(c=><div key={c.id} className="receipt-context"><span>{c.title}</span><p>{c.text}</p></div>)}{selected.length===0&&<p className="receipt-empty">No additional context included.</p>}<div className="receipt-seal"><LockKeyhole size={13}/> Email excluded</div></>}</div></section>
 </div><div className="boundary-footnote"><span>This preview stays in your browser. Only selected context is included.</span><a href="#workspace-preview">CONTINUE EXPLORING <span>↓</span></a></div>
 </section>
}
