 'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Check,Code2,PenLine,RotateCcw,LockKeyhole} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {homeRequests,requestAgent} from '@/lib/home-requests';
import {WorkedOutput} from './worked-output';
import {guidedResults,matchesWorkedRequest} from '@/lib/guided-results';
import {getAgent,withAgent} from '@/lib/agents';
import {buildPayload,maskIdentifiers,newId} from '@/lib/workspace';
import {createRequestReview,hasReviewApproval,type RequestReview} from '@/lib/request-review';
import {useWorkspace} from './store';
import {RequestReceipt} from './request-receipt';
import {ServiceNotice} from './service-notice';
const cases=homeRequests.map(request=>({id:request.id,agent:requestAgent(request),title:request.title,summary:request.description,Icon:request.category==='Coding'?Code2:PenLine,result:guidedResults[request.id].title}));
const steps=['Choose a task','Write the prompt','Select context','Review & approve','Run the agent'];
export function GuidedWalkthrough(){
 const s=useWorkspace();const[caseId,setCaseId]=useState(cases[0].id);const[step,setStep]=useState(0);const[prompt,setPrompt]=useState(homeRequests.find(x=>x.id===cases[0].id)!.prompt);const[selected,setSelected]=useState<string[]>([]);const[review,setReview]=useState<RequestReview|null>(null);const[action,setAction]=useState<string|null>(null);const[error,setError]=useState('');const[maskNote,setMaskNote]=useState('');const[outputKey,setOutputKey]=useState<string|null>(null);const heading=useRef<HTMLHeadingElement>(null);
 const scenario=cases.find(x=>x.id===caseId)!;const example=homeRequests.find(x=>x.id===caseId)!;const agent=getAgent(scenario.agent);const payload=withAgent(buildPayload(agent.model,prompt,example.context,selected,[],[]),agent.id);const key=JSON.stringify(payload);const approved=hasReviewApproval(review,key);const included=example.context.filter(x=>selected.includes(x.id));const expectedPayload=withAgent(buildPayload(agent.model,example.prompt,example.context,example.context.slice(0,2).map(item=>item.id),[],[]),agent.id);const hasWorkedOutput=matchesWorkedRequest(payload,expectedPayload);const showOutput=approved&&outputKey===key;
 useEffect(()=>{setReview(null);setOutputKey(null)},[key]);
 const move=(next:number)=>{setStep(next);setError('');requestAnimationFrame(()=>heading.current?.focus())};
 const choose=(id:string)=>{const next=homeRequests.find(x=>x.id===id)!;setCaseId(id);setPrompt(next.prompt);setSelected([]);setReview(null);setOutputKey(null);setMaskNote('');setError('')};
 const advance=()=>{if(step===1&&!prompt.trim())return;if(step===2)setReview(createRequestReview(key,payload));if(step===3&&!approved)return;move(step+1)};
 const reset=()=>{choose(caseId);move(0)};
 const loadWorkedInputs=()=>{setPrompt(example.prompt);setSelected(example.context.slice(0,2).map(item=>item.id));setReview(null);setOutputKey(null);setMaskNote('');move(2)};
 const run=()=>{if(!approved||!prompt.trim())return;if(hasWorkedOutput)setOutputKey(key);setAction(agent.name)};
 return <div className="guided-walkthrough"><div className="walkthrough-topline"><span>5 steps · no wallet required</span><button className="button ghost small" onClick={reset}><RotateCcw size={14}/>Start again</button></div><ol className="walkthrough-steps" aria-label="Walkthrough progress">{steps.map((name,index)=><li key={name}><button disabled={index>step} aria-current={index===step?'step':undefined} onClick={()=>move(index)}><span>{index<step?<Check size={15}/>:String(index+1).padStart(2,'0')}</span><strong>{name}</strong></button></li>)}</ol><div className="walkthrough-layout"><section className="panel walkthrough-task"><div className="eyebrow">STEP {step+1} / 5</div><h2 ref={heading} tabIndex={-1}>{steps[step]}</h2>
 {step===0&&<><p>Pick a task you could encounter at work. These prepared scenarios are editable starting points.</p><div className="walkthrough-cases">{cases.map(({id,title,summary,Icon})=><button key={id} aria-pressed={id===caseId} onClick={()=>choose(id)}><Icon size={22}/><span><strong>{title}</strong><small>{summary}</small></span>{id===caseId&&<Check size={17}/>}</button>)}</div><div className="walkthrough-agent"><strong>{agent.name}</strong><p>{agent.description}</p><details><summary>Agent instructions</summary><p>{agent.instruction}</p></details></div></>}
 {step===1&&<><p>Describe the outcome you need. Anything you type into the prompt is included in the request.</p><label className="walkthrough-label" htmlFor="walkthrough-prompt">Your prompt</label><textarea id="walkthrough-prompt" value={prompt} maxLength={10000} onChange={e=>{setPrompt(e.target.value);setMaskNote('')}} rows={7}/><div className="walkthrough-prompt-tools"><button className="button secondary small" disabled={!prompt.trim()} onClick={()=>{setPrompt(maskIdentifiers(prompt));setMaskNote('Common email and phone patterns checked. Inspect the remaining text for identifying details.')}}>Mask identifiers</button><span>{prompt.length.toLocaleString()} / 10,000</span></div>{maskNote&&<p role="status" className="caption">{maskNote}</p>}</>}
 {step===2&&<><p>Every item starts excluded. Select only what the task needs. Titles and body text are both included when selected.</p><div className="walkthrough-context">{example.context.map(item=><label key={item.id} className={selected.includes(item.id)?'included':''}><Checkbox checked={selected.includes(item.id)} onCheckedChange={checked=>setSelected(list=>checked===true?[...list.filter(id=>id!==item.id),item.id]:list.filter(id=>id!==item.id))}/><span><strong>{item.title}<small>{selected.includes(item.id)?'Included':'Excluded'}</small></strong><span>{item.body}</span></span></label>)}</div><p className="caption">For the worked output, select the first two items and leave the separate record excluded. Masking the prompt does not mask these context items.</p></>}
 {step===3&&<>{review?.key===key&&<RequestReceipt payload={review.payload} external={false} contextCount={included.length} historyCount={0} workflowInput={false} sending={false} approved={approved} onApproval={value=>setReview(current=>current?.key===key?{...current,approved:value}:null)}/>}</>}
 {step===4&&<><div className="walkthrough-ready"><Check size={24}/><div><strong>Your request is approved.</strong><p>{agent.name} · {included.length} context {included.length===1?'item':'items'} · no history</p></div></div><h3>Requested outcome</h3><p>{scenario.result}</p><p className="walkthrough-final-note">Your draft is preserved. Run the agent to continue, or take this request into the workspace.</p><button className="button primary" disabled={!approved||!prompt.trim()} onClick={run}>Run {agent.name}</button>{!hasWorkedOutput&&<div className="walkthrough-output-inputs"><p>The worked output uses the original prompt and the first two context items. Load those inputs if you want to follow the original example.</p><button className="button secondary small" onClick={loadWorkedInputs}>Load worked inputs for review</button></div>}{showOutput&&<WorkedOutput requestId={caseId}/>}<Link className="walkthrough-workspace-link text-link" href="/workspace" onClick={event=>{const chosen=included.map(item=>({...item,id:newId()}));if(chosen.length&&!s.saveItems([...s.items,...chosen])){event.preventDefault();setError('Context could not be saved. Your walkthrough draft is preserved.');return}s.setAgent(agent.id);s.setModel(agent.model);s.setPrompt(prompt);s.setSelected(chosen.map(x=>x.id));s.setSelectedTurns([])}}>Continue in workspace</Link></>}
 {error&&<p role="alert" className="error-text">{error}</p>}<div className="walkthrough-navigation">{step>0&&<button className="button secondary" onClick={()=>move(step-1)}>Back</button>}{step<4&&<button className="button primary" disabled={step===1&&!prompt.trim()||step===3&&!approved} onClick={advance}>{step===3?'Continue to execution':'Continue'}</button>}</div></section><aside className="panel walkthrough-summary"><div className="eyebrow">YOUR REQUEST BOUNDARY</div><h3>{scenario.title}</h3><dl><div><dt>Agent</dt><dd>{agent.name}</dd></div><div><dt>Context included</dt><dd>{included.length} of {example.context.length}</dd></div><div><dt>Conversation history</dt><dd>None</dd></div><div><dt>Approval</dt><dd>{approved?'Approved by you':'Awaiting review'}</dd></div></dl><h4>Included context</h4>{included.length?<ul>{included.map(item=><li key={item.id}>{item.title}</li>)}</ul>:<p>No context selected.</p>}<h4>Excluded context</h4>{example.context.some(item=>!selected.includes(item.id))?<ul>{example.context.filter(item=>!selected.includes(item.id)).map(item=><li key={item.id}>{item.title}</li>)}</ul>:<p>All context selected. Inspect each item carefully.</p>}<div className="walkthrough-boundary-note"><LockKeyhole size={19}/><p>Preparing and reviewing this request stays on your device. A provider can read text you approve for submission.</p></div><a className="text-link" href="/privacy">Understand the data boundaries</a></aside></div><ServiceNotice action={action} detail={action&&!hasWorkedOutput?'A fresh answer to your edited request needs live AI. Your draft is preserved. The prepared result uses the original prompt and the first two context items.':undefined} continueLabel={showOutput?'View example result':'Continue exploring'} onClose={()=>{setAction(null);if(showOutput)requestAnimationFrame(()=>document.getElementById('worked-output-title')?.focus())}}/></div>;
}
