'use client';
import {useEffect,useState,useRef,lazy,Suspense,createContext,useContext} from 'react';
import {usePathname} from 'next/navigation';
import {Menu,X,Wallet} from 'lucide-react';
import {Toaster} from '@/components/ui/sonner';
import {Brand,Mark,whitepaper} from './shared';
import {WorkspaceProvider} from './store';
import {SocialLinks} from './social-links';
import {ContractAddress} from './contract-address';
import {X_URL,GITHUB_URL} from '@/lib/project-links';
const WalletControls=createContext<(()=>void)|null>(null);
export function useWalletControls(){const open=useContext(WalletControls);if(!open)throw Error('Wallet controls missing');return open;}
const WalletModal=lazy(()=>import('./wallet'));
const links=[['Workspace','/workspace'],['Privacy','/privacy'],['Developers','/developers'],['Tokenomics','/tokenomics'],['Whitepaper','/whitepaper']];
export function Shell({children}:{children:React.ReactNode}){const path=usePathname();const[wallet,setWallet]=useState(false);const[walletLoaded,setWalletLoaded]=useState(false);const wipe=useRef<HTMLDivElement>(null);const previous=useRef(path);
useEffect(()=>{document.title=(path==='/'?'Anonyx — Choose what you share':`${links.find(x=>x[1]===path)?.[0]||'Privacy Policy'} · Anonyx`);if(previous.current!==path){previous.current=path;const main=document.getElementById('main');main?.focus({preventScroll:true});if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){import('gsap').then(({gsap})=>{gsap.killTweensOf(wipe.current);gsap.fromTo(wipe.current,{yPercent:100},{yPercent:-100,duration:.48,ease:'power3.inOut'});gsap.fromTo('#main',{opacity:.55},{opacity:1,duration:.4,clearProps:'opacity'})})}}},[path]);
const openWallet=()=>{setWalletLoaded(true);setWallet(true)};
return <WorkspaceProvider><WalletControls.Provider value={openWallet}><a href="#main" className="skip">Skip to content</a>{path!=='/workspace'&&<header className="site-header project-navbar"><Brand/><nav className="site-nav" aria-label="Main navigation">{links.map(([name,url])=><a key={url} href={url} target={url===GITHUB_URL?'_blank':undefined} rel={url===GITHUB_URL?'noopener noreferrer':undefined} aria-label={url===GITHUB_URL?'Anonyx on GitHub (opens in a new tab)':undefined} className={path===url?'current':''} aria-current={path===url?'page':undefined}>{name}</a>)}</nav><div className="navbar-address"><ContractAddress navbar/></div><div className="header-right"><SocialLinks/><button className="button secondary small" onClick={()=>{setWalletLoaded(true);setWallet(true)}}><Wallet size={15}/>Connect Wallet</button><details className="mobile-navigation"><summary aria-label="Open navigation"><Menu size={22}/><span>Menu</span></summary><nav className="mobile-nav" aria-label="Mobile navigation">{links.map(([name,url])=><a key={url} href={url} target={url===GITHUB_URL?'_blank':undefined} rel={url===GITHUB_URL?'noopener noreferrer':undefined} aria-label={url===GITHUB_URL?'Anonyx on GitHub (opens in a new tab)':undefined} aria-current={path===url?'page':undefined}>{name}</a>)}</nav></details></div></header>}<main id="main" tabIndex={-1} className={path==='/workspace'?'workspace-route':undefined}>{children}</main>{path!=='/workspace'&&<footer className="site-footer"><div className="footer-top"><Brand/><p>Intelligence, with boundaries.</p></div><div className="footer-links"><a href="/workspace">Workspace</a><a href="/developers">Developers</a><a href="/whitepaper">Whitepaper</a><a href="/privacy-policy">Privacy Policy</a><a href={X_URL} target="_blank" rel="noopener noreferrer">Anonyx on X</a></div><div className="footer-contract"><ContractAddress/></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Anonyx · Team AP</span><span>Privacy-aware AI infrastructure · Robinhood Chain</span></div></footer>}<div ref={wipe} className="route-wipe" aria-hidden="true"/>{walletLoaded&&<Suspense fallback={wallet?<div className="wallet-loading" role="status">Loading wallet options…<button onClick={()=>setWallet(false)}>Dismiss</button></div>:null}><WalletModal open={wallet} onOpenChange={setWallet}/></Suspense>}<Toaster theme="dark" richColors position="bottom-right"/></WalletControls.Provider></WorkspaceProvider>}
