'use client';
import {createContext,useContext,useEffect,useRef,useState,ReactNode} from 'react';
import {ContextItem,Turn,STORAGE_KEY,validateContext} from '@/lib/workspace';
type State={agent:string;setAgent:(id:string)=>void;prompt:string;setPrompt:(s:string)=>void;model:string;setModel:(s:string)=>void;items:ContextItem[];saveItems:(items:ContextItem[])=>boolean;persist:boolean;setPersist:(v:boolean)=>void;selected:string[];setSelected:(s:string[])=>void;turns:Turn[];setTurns:React.Dispatch<React.SetStateAction<Turn[]>>;selectedTurns:string[];setSelectedTurns:(s:string[])=>void;storageError:string;epoch:React.MutableRefObject<number>;endSession:()=>void;ready:boolean};
const Store=createContext<State|null>(null);
export function WorkspaceProvider({children}:{children:ReactNode}){const[agent,setAgent]=useState('general');const[prompt,setPrompt]=useState('');const[model,setModel]=useState('anonyx-balanced');const[items,setItems]=useState<ContextItem[]>([]);const[persist,setPersistent]=useState(false);const[selected,setSelected]=useState<string[]>([]);const[turns,setTurns]=useState<Turn[]>([]);const[selectedTurns,setSelectedTurns]=useState<string[]>([]);const[storageError,setError]=useState('');const[ready,setReady]=useState(false);const epoch=useRef(0);
useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){if(raw.length>1048576)throw Error();setItems(validateContext(JSON.parse(raw)));setPersistent(true)}}catch{setError('Saved context could not be loaded. Your session can still run in memory.')}setReady(true)},[]);
const saveItems=(next:ContextItem[])=>{try{validateContext({version:1,items:next})}catch(e){setError((e as Error).message);return false}setItems(next);setSelected(s=>s.filter(id=>next.some(x=>x.id===id)));if(persist){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,items:next}));setError('')}catch{setError('Browser storage failed. Changes exist only in memory; previously saved data may still be on this device.');return false}}return true};
const setPersist=(enabled:boolean)=>{try{if(enabled)localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,items}));else localStorage.removeItem(STORAGE_KEY);setPersistent(enabled);setError('')}catch{setError('Could not change browser storage. Saved data may still exist.')}};
const endSession=()=>{epoch.current++;setPrompt('');setSelected([]);setSelectedTurns([]);setTurns([])};
return <Store.Provider value={{agent,setAgent,prompt,setPrompt,model,setModel,items,saveItems,persist,setPersist,selected,setSelected,turns,setTurns,selectedTurns,setSelectedTurns,storageError,epoch,endSession,ready}}>{children}</Store.Provider>}
export function useWorkspace(){const ctx=useContext(Store);if(!ctx)throw Error('Workspace provider missing');return ctx}
