import {PageIntro} from '@/components/anonyx/shared';
export const metadata={title:'Privacy Policy'};
export default function Policy(){return <div className="page-wrap"><PageIntro eyebrow="DATA HANDLING" title="Privacy Policy" description="What this release stores, what it can send, and which controls are yours. Updated 7 October 2026."/><article className="document-body">{[
['Scope','This policy describes the Anonyx website and browser-based request controls, operated as a Team AP project. It does not establish confidentiality or anonymity guarantees for future protocol services. A public support contact and the legal operator details have not yet been supplied.'],
['Local request preparation','Prompt editing, masking, context selection, and payload inspection run in your browser. Preparing a request does not send it to an inference provider. The host still receives the ordinary network information needed to serve website pages and assets, such as your IP address and request metadata. Private preview hosting may require the host’s own sign-in.'],
['Drafts and transcripts','Workspace drafts, selected conversation turns, and transcripts remain in tab memory. Starting a new session clears Anonyx’s session state and ignores pending late responses. Reloading clears in-memory state. Page navigation may retain tab memory; use New session to clear the active session explicitly. It does not clear provider records, wallet/RPC metadata, browser history, downloads, or information stored by the hosting service.'],
['Saved context','Your context library is stored in memory by default. If you enable Remember context on this device after reviewing the local-storage notice, Anonyx writes the library to localStorage under an Anonyx-specific key. This storage is not encrypted at rest and is specific to the browser and device. Other people with access to your browser profile may be able to read it. There is no Anonyx cloud sync or database.'],
['Selection and deletion','Only context and conversation turns you select are included in a request preview. Delete an individual context item or choose Delete All Saved Context to remove the browser copy. Disabling persistence removes the saved library while retaining the current in-memory items. Storage failures are reported instead of being presented as successful deletion.'],
['Import and export','JSON import reads a file locally and requires a review before applying changes. Exports contain the context items you select. Exported files remain wherever your browser saves them until you delete them yourself.'],
['External inference','The workspace checks provider configuration without sending your draft or context. When enabled, approved requests pass through Anonyx’s server-side gateway to the configured AI provider. The server therefore processes the approved text transiently; it does not write prompt content to an application database or application logs. The provider key stays on the server. Live access requires a signed-in, allowlisted account; the authentication identifier is used for access and burst control and is not appended to the model messages. Each request requires review and approval, and edits invalidate that approval. Only the reviewed model and message fields reach the provider. Provider retention and data-use terms apply; Anonyx cannot erase its records. Unconfigured final actions show a coming-soon notice and preserve the draft.'],
['Wallets and RPC','Opening wallet controls loads the wallet integration. Connecting uses your chosen wallet and can reveal your address and network information to the wallet and the RPC provider used for balance reads. Connected wallet fields are not automatically added to AI request payloads. Wallet addresses you type into a prompt or select as context are included in that text. This website requests no funding transaction, token approval, or spending signature. Disconnect ends the application connection; it does not erase third-party logs. WalletConnect is hidden unless configured.'],
['Measurement and third-party services','Anonyx does not implement product analytics, advertising trackers, or prompt logging. Fonts and the identity asset are served with the site. The hosting platform and optional wallet/provider services operate under their own policies. External whitepaper links open Google Docs. No prompts or saved context are placed onchain, in URLs, or in application analytics.'],
['Limits and updates','Pattern-based masking can miss sensitive information. A local private session is not a guarantee of anonymity, confidential computing, or provider non-retention. This policy must be updated before changing storage, inference providers, analytics, or settlement behavior.']
].map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}</article></div>}
