import type {RequestPayload} from './workspace';
export const agents = [
 {id:'general',name:'Anonyx Assistant',role:'Everyday questions',description:'Explain an idea, explore a question, or find a useful next step.',model:'anonyx-balanced',example:'Explain how selective context works in plain language.',instruction:'Answer the user’s question clearly. Use only the supplied request and selected context. Ask for missing information rather than inventing facts.'},
 {id:'research',name:'Research Agent',role:'Research & synthesis',description:'Organize source notes, compare findings, and identify gaps.',model:'anonyx-balanced',example:'Synthesize my selected research notes. Separate findings, uncertainties, and open questions.',instruction:'Synthesize only supplied source material. Distinguish evidence from inference, identify gaps, and never invent citations or imply you browsed the web.'},
 {id:'writing',name:'Writing Agent',role:'Draft & refine',description:'Shape clear drafts, edit tone, and keep your intended meaning.',model:'anonyx-writing',example:'Turn my selected brief into a concise project introduction. Keep the claims factual.',instruction:'Help draft or revise text in the requested tone. Preserve the intended meaning, use supplied facts, and avoid unsupported claims.'},
 {id:'coding',name:'Code Agent',role:'Review & debug',description:'Inspect code, reason through bugs, and suggest focused fixes.',model:'anonyx-coding',example:'Review the code I provide for correctness and input validation. Explain each suggested fix.',instruction:'Review supplied code and requirements. Explain likely causes and focused fixes. Clearly distinguish reasoning from executed tests; do not claim to have run code.'},
 {id:'analysis',name:'Analysis Agent',role:'Compare & evaluate',description:'Weigh options, structure evidence, and explain trade-offs.',model:'anonyx-balanced',example:'Compare the options in my selected context using a table. List assumptions and missing information.',instruction:'Analyze supplied information using explicit criteria. Separate facts, assumptions, and uncertainties. Do not invent numbers or evidence.'},
 {id:'planning',name:'Planning Agent',role:'Plan & organize',description:'Turn goals and constraints into practical, ordered steps.',model:'anonyx-balanced',example:'Build an actionable plan from my selected goals and constraints. Include dependencies and open decisions.',instruction:'Create a practical plan from the supplied goals and constraints. Identify dependencies and missing decisions. Do not imply that tasks have been executed.'},
] as const;
export function getAgent(id:string){return agents.find(agent=>agent.id===id)||agents[0]}
export function withAgent(payload:RequestPayload,id:string):RequestPayload{
 const agent=getAgent(id);
 return {...payload,messages:[{role:'system',content:`Anonyx agent: ${agent.name}\n${agent.instruction}`},...payload.messages]};
}
