import type {ContextItem} from './workspace';
export type HomeRequest={id:string;title:string;category:string;model:string;prompt:string;description:string;context:ContextItem[]};
export function requestAgent(request:HomeRequest){return request.id==='study-plan'?'planning':request.model==='anonyx-coding'?'coding':request.model==='anonyx-writing'?'writing':request.category==='Research'?'research':'analysis'}
function context(prefix:string,items:[string,string,string][]):ContextItem[]{return items.map(([title,body,type],index)=>({id:`${prefix}-${index}`,title,body,type,tags:['example']}))}
export const homeRequests:HomeRequest[]=[
 {id:'client-brief',title:'Client brief',category:'Writing',model:'anonyx-writing',prompt:'Write a client brief for the Northstar portal launch using the selected project details. Cover the goal, launch scope, next milestones, and decisions needed. Keep it under 200 words.',description:'Give the model the launch scope and writing preferences. Contact details are a separate choice.',context:context('client-brief',[
 ['Launch scope','Northstar is replacing email-based client updates with a portal. The first release includes project status, document sharing, and milestone approvals. Billing stays outside this release.','Project'],
 ['Milestones and tone','Prototype review: 14 October. Client feedback closes: 21 October. Target rollout: 4 November. Use clear, confident language and ask the client to confirm the approval workflow.','Preference'],
 ['Contact details','Project contact: alex@example.com. Phone: +1 (415) 555-0198. Internal account reference: NS-2048.','Reference']])},
 {id:'project-update',title:'Project update',category:'Writing',model:'anonyx-writing',prompt:'Turn the selected delivery notes into a weekly project update. Separate completed work, blockers, and next steps. Highlight decisions needed without inventing progress.',description:'Share delivery notes and the update format. Keep unrelated commercial details separate.',context:context('project-update',[
 ['Delivery notes','Completed: account settings and context export. In progress: mobile navigation. Blocker: final copy for onboarding. Next: accessibility review and browser checks.','Project'],
 ['Update format','Audience: product and engineering leads. Use three short headings: Completed, Blockers, Next. End with a request to approve onboarding copy by Friday.','Preference'],
 ['Commercial notes','Draft renewal budget: $24,000. Procurement contact: buyer@example.com. These notes are unrelated to the delivery update.','Reference']])},
 {id:'meeting-notes',title:'Meeting actions',category:'Analysis',model:'anonyx-balanced',prompt:'Extract decisions and action items from the selected meeting notes. Give each action an owner role and due date when provided. Mark missing owners or dates as unspecified.',description:'Include the meeting notes and action format. The attendee contact list can stay excluded.',context:context('meeting-notes',[
 ['Planning meeting','7 October: approved a smaller onboarding flow. Product lead will deliver revised copy by 9 October. Engineering lead will estimate implementation by 12 October. QA will prepare regression cases; no deadline was agreed.','Project'],
 ['Action format','Return Decisions first, then an action table with Task, Owner role, Due date. Do not infer names, commitments, or dates absent from the notes.','Preference'],
 ['Attendee contacts','Product: product@example.com. Engineering: engineering@example.com. QA: qa@example.com.','Reference']])},
 {id:'code-review',title:'Code review',category:'Coding',model:'anonyx-coding',prompt:'Review the selected TypeScript function for correctness and input handling. Explain the main risks, suggest a small fix, and give useful test cases. Preserve the public function signature.',description:'Share the function and its expected behavior. Environment and account details are not needed.',context:context('code-review',[
 ['Function to review','export function paginate<T>(items: T[], page: number, size: number) { return items.slice((page - 1) * size, page * size); }','Code'],
 ['Expected behavior','Page numbers start at 1. Page and size must be positive integers. Invalid inputs should throw a descriptive error. An out-of-range page returns an empty array. Do not mutate items.','Project'],
 ['Deployment notes','Internal environment label: customer-portal-prod. Operations contact: ops@example.com. Account reference: CP-482.','Reference']])},
 {id:'bug-diagnosis',title:'Bug diagnosis',category:'Coding',model:'anonyx-coding',prompt:'Diagnose why search results sometimes show an older query. Use the selected code and reproduction notes. Suggest a fix that handles cancellation and component unmounting, and describe how to verify it.',description:'Provide the fetch effect and reproduction steps. User records can stay out of the request.',context:context('bug-diagnosis',[
 ['Search effect','useEffect(() => { fetch(`/api/search?q=${encodeURIComponent(query)}`).then(r => r.json()).then(setResults); }, [query]);','Code'],
 ['Reproduction','Type “context”, then quickly replace it with “privacy”. The first request sometimes finishes last and overwrites the newer results. The component can unmount while a request is pending.','Project'],
 ['User record','Reported by support-user@example.com. Internal support record: SR-1182. Browser profile contains saved customer context.','Reference']])},
 {id:'research-summary',title:'Research synthesis',category:'Research',model:'anonyx-balanced',prompt:'Summarize the selected research observations into themes and product implications. Distinguish observed findings from hypotheses. Avoid claiming that this small sample represents all users.',description:'Use the observations and research scope. Participant identifiers are stored separately.',context:context('research-summary',[
 ['Research observations','In five interviews, four participants wanted to inspect outgoing context. Three found automatic history inclusion confusing. Two preferred context persistence, but only after a clear storage explanation.','Research'],
 ['Research scope','Exploratory interviews with five experienced AI users. No quantitative survey or representative sampling. Produce three themes, supporting observations, and one follow-up question per theme.','Preference'],
 ['Participant records','Participant contact: researcher-contact@example.com. Recruitment reference: INT-007. Raw identifiers are not needed for the summary.','Reference']])},
 {id:'product-comparison',title:'Compare options',category:'Analysis',model:'anonyx-balanced',prompt:'Compare the two selected context-storage proposals against the selected team requirements. Explain tradeoffs, recommend an option, and list what must be validated before adoption. Use only the supplied information.',description:'Compare concrete options and requirements. Unrelated company account details stay separate.',context:context('product-comparison',[
 ['Storage proposals','Option A: browser-only context, no cross-device sync, minimal server infrastructure. Option B: encrypted cloud sync, shared access controls, added key-management and recovery requirements. Neither option has completed a security review.','Project'],
 ['Team requirements','Four-person team. Cross-device access is useful, but reducing infrastructure exposure is the first priority. Shared context is not required for the initial release. The team can manage manual exports.','Preference'],
 ['Company account','Billing contact: finance@example.com. Internal procurement reference: PO-621. These details do not affect the technical comparison.','Reference']])},
 {id:'customer-reply',title:'Customer reply',category:'Writing',model:'anonyx-writing',prompt:'Draft a helpful reply to the selected support issue using the selected product policy. Give clear next steps, acknowledge the inconvenience, and avoid promising recovery or timelines not supported by the policy.',description:'Share the issue and approved policy. Keep the customer’s account details excluded.',context:context('customer-reply',[
 ['Support issue','A user enabled context storage, switched browser profiles, and can no longer see the saved library. They ask whether their context was deleted and how to get it back.','Project'],
 ['Product policy','Saved context is specific to the browser profile and device. There is no cloud sync. Ask the user to check the original profile and any exported JSON files. Do not guarantee recovery. Use a warm, concise tone.','Preference'],
 ['Customer account','Email: customer@example.com. Account reference: AC-3891. Telephone: +1 (212) 555-0144.','Reference']])},
 {id:'study-plan',title:'Study plan',category:'Learning',model:'anonyx-balanced',prompt:'Create a two-week study plan using the selected learning goal and available time. Include daily practice, two checkpoints, and a final small project. Keep the workload within the stated schedule.',description:'Provide learning goals and availability. Personal contact information is unnecessary.',context:context('study-plan',[
 ['Learning goal','Learn TypeScript fundamentals: types, unions, interfaces, generics, and safe handling of unknown input. Existing experience: basic JavaScript functions and arrays. Final project: a typed context-item validator.','Project'],
 ['Available time','45 minutes on weekdays, 90 minutes on Saturdays, Sundays off. Prefer short exercises and examples over long lectures. Include time for revision.','Preference'],
 ['Personal details','Learner email: student@example.com. Personal scheduling reference: CAL-129. Contact details are not needed for a study plan.','Reference']])},
 {id:'rewrite-text',title:'Rewrite text',category:'Writing',model:'anonyx-writing',prompt:'Rewrite the selected draft for a general audience using the selected style preferences. Preserve its meaning and limitations. Return the revised paragraph and briefly explain the most important wording changes.',description:'Share the draft and writing rules. Internal approval contacts remain separate.',context:context('rewrite-text',[
 ['Draft paragraph','Our system facilitates granular contextual disclosure by allowing explicit user-mediated payload construction. The mechanism minimizes extraneous contextual transmission but does not guarantee non-retention by downstream inference providers.','Writing'],
 ['Style preferences','Use plain English, active voice, and short sentences. Avoid jargon and absolute privacy claims. Keep the rewritten paragraph under 80 words.','Preference'],
 ['Internal approval','Reviewer: editor@example.com. Internal draft reference: DOC-319. The review contact does not need to appear in the rewritten paragraph.','Reference']])},
];
