import {newId} from '@/lib/workspace';
import type {RequestPayload} from './workspace';
export type LiveModel={id:string;name:string;provider:string};
export const ADAPTER_ORIGIN=process.env.NEXT_PUBLIC_INFERENCE_ADAPTER_ORIGIN||'';
export const LIVE_ENABLED=process.env.NEXT_PUBLIC_INFERENCE_VERIFIED==='true'&&!!ADAPTER_ORIGIN;
export class InferenceBridge{private popup:Window|null=null;private origin:string;constructor(){if(!LIVE_ENABLED)throw Error('External inference is not configured for this release.');this.origin=new URL(ADAPTER_ORIGIN).origin;if(this.origin===location.origin||!this.origin.startsWith('https://'))throw Error('The provider adapter must have a separate HTTPS origin.')}
open(){this.popup=window.open(this.origin,'anonyx-inference','popup,width=520,height=650');if(!this.popup)throw Error('Allow the provider popup, then try again.');return this}
request<T>(kind:'catalog'|'chat',payload?:RequestPayload):Promise<T>{return new Promise((resolve,reject)=>{const popup=this.popup;if(!popup||popup.closed)return reject(Error('The provider window is closed. Enable external mode again.'));const id=newId();let sent=false;const clean=()=>{clearTimeout(timer);clearInterval(ping);window.removeEventListener('message',receive)};const receive=(e:MessageEvent)=>{if(e.origin!==this.origin||e.source!==popup||!e.data||e.data.channel!=='anonyx-v1')return;if(e.data.type==='ready'&&!sent){sent=true;clearInterval(ping);popup.postMessage({channel:'anonyx-v1',id,kind,...(payload?{payload}:{})},this.origin)}if(e.data.id===id&&e.data.type==='result'){clean();if(e.data.error)reject(Error(String(e.data.error)));else resolve(e.data.result as T)}};const timer=setTimeout(()=>{clean();reject(Error('The provider did not respond. Your draft is preserved. Retry only if you want to make another request.'))},90000);const ping=setInterval(()=>popup.postMessage({channel:'anonyx-v1',type:'ping'},this.origin),500);window.addEventListener('message',receive);popup.postMessage({channel:'anonyx-v1',type:'ping'},this.origin)})}
close(){this.popup?.close();this.popup=null}}
