export type ContextItem={id:string;title:string;body:string;type:string;tags:string[]};
export type Turn={id:string;role:'user'|'assistant';content:string;model:string;mode:'demo'|'external'};
export type RequestPayload={model:string;provider?:string;messages:{role:'system'|'user'|'assistant';content:string}[]};
export const demoModels=[{value:'anonyx-balanced',label:'Balanced'},{value:'anonyx-writing',label:'Writing'},{value:'anonyx-coding',label:'Coding'}];
export const STORAGE_KEY='anonyx.context.v1';
export function maskIdentifiers(text:string){return text.replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[EMAIL]').replace(/(?<!\w)(?:\+?\d[\d ()-]{6,}\d)(?!\w)/g,m=>m.replace(/\D/g,'').length>=8?'[PHONE]':m)}
export function validateContext(value:unknown):ContextItem[]{if(!value||typeof value!=='object'||(value as {version?:number}).version!==1||!Array.isArray((value as {items?:unknown}).items))throw new Error('Use a version 1 Anonyx context export.');const items=(value as {items:unknown[]}).items;if(items.length>100)throw new Error('A maximum of 100 items is allowed.');const ids=new Set<string>();return items.map(item=>{if(!item||typeof item!=='object')throw new Error('Invalid context item.');const x=item as ContextItem;if(typeof x.id!=='string'||!x.id||x.id.length>100||ids.has(x.id))throw new Error('Missing or duplicate item ID.');ids.add(x.id);if(typeof x.title!=='string'||!x.title.trim()||x.title.length>80||typeof x.body!=='string'||x.body.length>10000||typeof x.type!=='string'||x.type.length>40||!Array.isArray(x.tags)||x.tags.length>20||x.tags.some(t=>typeof t!=='string'||t.length>80))throw new Error('An item exceeds the supported limits or has invalid fields.');return{id:x.id,title:x.title.trim(),body:x.body,type:x.type,tags:x.tags}})}
export function buildPayload(model:string,prompt:string,items:ContextItem[],selected:string[],turns:Turn[],selectedTurns:string[],provider?:string):RequestPayload {const chosen=items.filter(x=>selected.includes(x.id));const messages:RequestPayload['messages']=[];if(chosen.length)messages.push({role:'system',content:'User-selected context:\n'+chosen.map(x=>`${x.title}:\n${x.body}`).join('\n\n')});messages.push(...turns.filter(x=>selectedTurns.includes(x.id)).map(({role,content})=>({role,content})));messages.push({role:'user',content:prompt});return {model,...(provider?{provider}:{}),messages}}
export function simulate(payload:RequestPayload,stage='Response'){const prompt=payload.messages.at(-1)?.content||'';const contexts=payload.messages.filter(x=>x.role==='system').length;const intro=stage==='Critique'?'Illustrative critique: check clarity, assumptions, and the amount of context shared.':stage==='Refine'?'Illustrative refinement: lead with the purpose, keep the essentials, and remove unnecessary identifiers.':payload.model==='anonyx-coding'?'Example approach: define the inputs, validate them, handle errors, and verify the output.':payload.model==='anonyx-writing'?'Example outline: open with the main idea, add the essential context, and close with a clear next step.':'Example response: clarify your objective, choose the relevant information, and review the result.';return `${intro}\n\nYour reviewed prompt: “${prompt.slice(0,280)}${prompt.length>280?'…':''}”\n\n${contexts?'Your selected context is included in this local simulation.':'No saved context was included.'} This deterministic example demonstrates the request flow. It is not an AI-generated answer.`}

export function newId(){if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,v=>v.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
