 'use client';
import {useState} from 'react';
import {Coins,Vote,Layers3,Wallet} from 'lucide-react';
import {PageIntro,Mark,Picker} from '@/components/anonyx/shared';
import {ServiceNotice} from '@/components/anonyx/service-notice';
import {ContractAddress} from '@/components/anonyx/contract-address';
const settings=[
 ['Network','Robinhood Chain'],['Launch platform','Pons V2'],['Launch status','Planned launch'],
 ['Ticker','To be confirmed'],['Total supply','Selected launch configuration'],['Pairing asset','To be confirmed'],
 ['Trading fees & creator tax','To be confirmed'],['Developer purchase','To be disclosed'],
];
export default function Tokenomics(){
 const[amount,setAmount]=useState('100');const[action,setAction]=useState<string|null>(null);
 return <div className="page-wrap"><PageIntro eyebrow="THE ANONYX ECONOMY" title="Tokenomics" description="Anonyx’s token launch is planned through Pons V2 on Robinhood Chain. Token distribution and AI resource access have separate roles."/>
 <div className="content-grid"><section className="panel"><div className="between"><div className="eyebrow" style={{margin:0}}>ANONYX TOKEN</div><Mark className="w-10 h-10 text-primary"/></div><div className="token-value">Anonyx</div><p>Launch specifications</p><dl className="token-launch-settings">{settings.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="token-contract"><h3>Contract address</h3><ContractAddress/></div></section>
 <section className="panel token-distribution"><div className="eyebrow">INITIAL DISTRIBUTION</div><h2>One launch mechanism.</h2><div className="token-distribution-total"><strong>100%</strong><span>Minted to the Pons V2 curve</span></div><div className="token-distribution-bar" aria-hidden="true"/><p>Includes the supply reserved for graduation liquidity. This does not mean 100% is sold to buyers.</p><div className="token-launch-phases"><div><span>01</span><strong>Bonding curve</strong><p>Initial trading.</p></div><div><span>02</span><strong>Graduation</strong><p>Transition to permanently locked Uniswap V4 liquidity.</p></div></div><p className="caption">Supply and reserve details depend on the selected launch configuration.</p><a className="text-link" href="https://docs.ponsfamily.com/v2" target="_blank" rel="noreferrer">Pons V2 launch documentation</a></section></div>
 <section className="panel mt"><div className="eyebrow">ECONOMIC DESIGN</div><h2>Clear responsibilities.</h2><div className="token-economic-grid"><article><h3>Distribution</h3><p>No separate team, treasury, or incentive allocation is specified. Any project-held tokens must be disclosed with their acquisition source and wallet.</p></article><article><h3>Project funding</h3><p>Trading proceeds and project operating funds must be accounted for separately. Anonyx has not committed a creator-fee budget, revenue split, or holder payout.</p></article><article><h3>Buybacks</h3><p>Pons V2 buybacks are optional and vest rather than burn. Anonyx’s setting is not confirmed.</p></article><article><h3>Launch transparency</h3><p>Publish the token address, selected terms, creator recipient, project purchases, and any exemptions when the launch is confirmed.</p></article></div></section>
 <section className="panel mt"><div className="eyebrow">UTILITY FRAMEWORK</div><h2>Resources with a purpose.</h2><div className="token-utility-grid">{[[Coins,'AI resource access','Eligible access rules must identify the service, required holdings or payment, and enforcement. A token balance is separate from AI credits.'],[Vote,'Protocol participation','Governance requires published decision scopes, voting rules, and administrative permissions. No voting rights are established by the launch alone.'],[Layers3,'Ecosystem incentives','Contributor rewards require a defined budget, eligibility, and distribution policy. No reward allocation or yield is promised.']].map(([Icon,title,description],i)=>{const I=Icon as typeof Coins;return <article key={i}><div className="flex-row"><I size={18} color="#b2a4ff"/><h3>{title as string}</h3></div><p>{description as string}</p></article>})}</div><p className="caption">These utilities depend on their supporting services. Token ownership does not guarantee AI availability, privacy, or investment returns.</p></section>
 <section className="panel mt"><div className="between mb"><div><div className="eyebrow">RESOURCE ACCESS</div><h2>Choose a resource request.</h2></div><span className="badge"><Wallet size={13}/>Your approval required</span></div><div className="content-grid"><div><Picker label="Requested credits" value={amount} onChange={setAmount} options={[{value:'25',label:'25 credits'},{value:'100',label:'100 credits'},{value:'250',label:'250 credits'}]}/><div className="button-row mt"><button className="button primary" onClick={()=>setAction(`Add ${amount} credits`)}>Add credits</button><button className="button secondary" onClick={()=>setAction('Redeem credits')}>Redeem credits</button></div><p className="caption">Credit selections are request amounts, not a token price or conversion quote.</p></div><div><h3>Before funding</h3><p>A service quote must identify the payment asset, credits received, total cost, expiry, and refund terms. No token-to-credit exchange rate is set here.</p><a className="text-link" href="/whitepaper#chapter-13">Read the economic framework</a></div></div></section><ServiceNotice action={action} onClose={()=>setAction(null)}/></div>;
}
