'use client';
import {useState} from 'react';
import {Copy,Download,Check,Code2} from 'lucide-react';
import {toast} from 'sonner';
import {PageIntro,Picker,download} from '@/components/anonyx/shared';
import {useWorkspace} from '@/components/anonyx/store';
import {buildPayload,demoModels} from '@/lib/workspace';
import {Checkbox} from '@/components/ui/checkbox';
import {ServiceNotice} from '@/components/anonyx/service-notice';
export default function Developers(){
 const s=useWorkspace();const[model,setModel]=useState('anonyx-balanced');const[prompt,setPrompt]=useState('Summarize the project goals in three clear points. Use only the selected context.');const[selected,setSelected]=useState<string[]>([]);const[manual,setManual]=useState<string|null>(null);const[scenario,setScenario]=useState('success');const[response,setResponse]=useState('');const[fallback,setFallback]=useState(false);const[action,setAction]=useState<string|null>(null);
 const generated=JSON.stringify(buildPayload(model,prompt,s.items,selected,[],[]),null,2);const json=manual??generated;let valid=true;try{const x=JSON.parse(json);valid=typeof x.model==='string'&&!!x.model&&Array.isArray(x.messages)&&x.messages.length>0&&x.messages.every((m:{role:string;content:string})=>['user','assistant','system'].includes(m.role)&&typeof m.content==='string')}catch{valid=false}
 const reset=()=>setManual(null);const copy=async()=>{try{await navigator.clipboard.writeText(json);toast.success('Request JSON copied.')}catch{setFallback(true);toast.info('Clipboard unavailable. Select and copy the JSON below.')}};
 const inspect=()=>{const contracts:Record<string,object>={success:{status:200,body:{request_id:'string',model:'string',output:'string',usage:{input_tokens:'number',output_tokens:'number'}}},invalid:{status:400,error:{code:'invalid_request',message:'A non-empty prompt is required.'}},quota:{status:429,error:{code:'quota_exceeded',message:'The request exceeds the configured resource limit.'}},failure:{status:503,error:{code:'service_unavailable',message:'The selected service cannot accept this request.'}}};setResponse(JSON.stringify(contracts[scenario],null,2))};
 return <div className="page-wrap"><PageIntro eyebrow="FOR DEVELOPERS" title="Build with the boundaries in view." description="Prepare requests on your device, choose only the context needed, and inspect the complete text before sharing."/>
 <div className="content-grid"><section className="panel"><h2>Request builder</h2><div className="mt mb"><Picker label="Model" value={model} onChange={v=>{setModel(v);reset()}} options={demoModels}/></div><div className="field"><label htmlFor="developer-prompt">Prompt</label><textarea id="developer-prompt" value={prompt} maxLength={10000} onChange={e=>{setPrompt(e.target.value);reset()}}/></div><h3 style={{fontSize:18}}>Include context</h3>{s.items.length?s.items.map(item=><div className="context-choice" key={item.id}><Checkbox id={'dev-'+item.id} checked={selected.includes(item.id)} onCheckedChange={v=>{setSelected(v?[...selected,item.id]:selected.filter(x=>x!==item.id));reset()}}/><label htmlFor={'dev-'+item.id}>{item.title}</label></div>):<p className="muted-text mt">Add context in the workspace, or keep this request context-free.</p>}<p className="caption">Changing a field regenerates the JSON. Connected wallet fields are not automatically added. Any identifiers you type into the prompt or JSON are included.</p></section>
 <section className="panel"><div className="between mb"><h2 style={{margin:0}}>Inspect the request</h2><span className="badge">{valid?'VALID JSON':'CHECK INPUT'}</span></div><div className="field"><label htmlFor="json-editor">Editable JSON</label><textarea id="json-editor" className="mono" style={{minHeight:300,fontSize:14}} value={json} onChange={e=>setManual(e.target.value)} aria-invalid={!valid}/></div>{!valid&&<p className="error-text mb">Enter valid JSON with a model and text messages.</p>}<div className="button-row"><button className="button primary small" disabled={!valid} onClick={copy}><Copy/>Copy JSON</button><button className="button secondary small" disabled={!valid} onClick={()=>download('anonyx-request.json',json)}><Download/>Download</button><button className="button ghost small" onClick={reset}>Reset</button></div>{fallback&&<div className="field mt"><label htmlFor="copy-fallback">Select and copy</label><textarea id="copy-fallback" readOnly value={json} onFocus={e=>e.target.select()}/></div>}<button className="button primary mt" disabled={!valid} onClick={()=>setAction('API request')}>Send request</button></section></div>
 <section className="panel mt"><div className="eyebrow">RESPONSE CONTRACTS</div><h2>Clear inputs. Predictable structure.</h2><p className="mb">Inspect the response format for each integration state.</p><div className="content-grid"><div><Picker label="Response format" value={scenario} onChange={v=>{setScenario(v);setResponse('')}} options={[{value:'success',label:'Success · 200'},{value:'invalid',label:'Invalid input · 400'},{value:'quota',label:'Quota exceeded · 429'},{value:'failure',label:'Service failure · 503'}]}/><button className="button secondary mt" onClick={inspect}>Inspect response format</button></div><pre className="json">{response||'Select a response format to inspect its fields.'}</pre></div></section>
 <section className="panel mt"><h2>Request controls</h2><ul className="info-list"><li><span>Model profiles</span>{demoModels.length}</li><li><span>Context included</span>{selected.filter(id=>s.items.some(item=>item.id===id)).length} items</li><li><span>Prompt size</span>{prompt.length.toLocaleString()} characters</li><li><span>Connected wallet fields</span>Not automatically added</li><li><span>Context storage</span>On this device</li></ul><button className="button secondary" onClick={()=>setAction('API credential creation')}>Create API credential</button></section><ServiceNotice action={action} onClose={()=>setAction(null)}/></div>;
}
