'use client';
import {newId} from '@/lib/workspace';
import {agents,getAgent,withAgent} from '@/lib/agents';
import {homeRequests,requestAgent,type HomeRequest} from '@/lib/home-requests';
import {matchesWorkedRequest} from '@/lib/guided-results';
import {WorkedOutput} from '@/components/anonyx/worked-output';
import {AgentOptions} from '@/components/anonyx/agent-options';
import {X_URL,GITHUB_URL} from '@/lib/project-links';
import {useEffect,useRef,useState} from 'react';
import {LockKeyhole,ScanLine,Undo2,Layers3,Eye,Plus,StopCircle,Workflow,MessageSquare,Check,Menu,X,Wallet,ShieldCheck,Code2,BookOpen,Coins,Home} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {useWorkspace} from '@/components/anonyx/store';
import {ContextManager} from '@/components/anonyx/context-manager';
import {useWalletControls} from '@/components/anonyx/shell';
import {Mark,Picker} from '@/components/anonyx/shared';
import {buildPayload,demoModels,maskIdentifiers,type Turn} from '@/lib/workspace';
import {ServiceNotice} from '@/components/anonyx/service-notice';
import {InferenceBridge,InferenceError,type LiveModel} from '@/lib/inference';
import {PrivacyStatus} from '@/components/anonyx/privacy-status';
import {RequestReceipt} from '@/components/anonyx/request-receipt';
import {createRequestReview,hasReviewApproval,type RequestReview} from '@/lib/request-review';
export default function Workspace(){const s=useWorkspace();const currentDraft=useRef(s.prompt);currentDraft.current=s.prompt;const openWallet=useWalletControls();const[sidebarOpen,setSidebarOpen]=useState(false);const[contextOpen,setContextOpen]=useState(false);const[privacyOpen,setPrivacyOpen]=useState(false);const[reviewOpen,setReviewOpen]=useState(false);const[resetOpen,setResetOpen]=useState(false);const[resetIntent,setResetIntent]=useState<'new'|'end'>('new');const[smallScreen,setSmallScreen]=useState(false);const menuButton=useRef<HTMLButtonElement>(null);const wasSidebarOpen=useRef(false);const[action,setAction]=useState<string|null>(null);const[exampleResult,setExampleResult]=useState<{id:string;key:string}|null>(null);const[tab,setTab]=useState('compose');const[mode,setMode]=useState<'demo'|'external'>('demo');const[original,setOriginal]=useState<string|null>(null);const[review,setReview]=useState<RequestReview|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[disclosure,setDisclosure]=useState(false);const[models,setModels]=useState<LiveModel[]>([]);const[catalogLoading,setCatalogLoading]=useState(false);const[toolsOpen,setToolsOpen]=useState(false);const[flow,setFlow]=useState('compare');const[stage,setStage]=useState(0);const[flowOutputs,setFlowOutputs]=useState<Turn[]>([]);const[second,setSecond]=useState('anonyx-writing');const[inputSearch,setInputSearch]=useState('');const textarea=useRef<HTMLTextAreaElement>(null);const bridge=useRef<InferenceBridge|null>(null);const requestId=useRef(0);const catalogId=useRef(0);const alive=useRef(true);
useEffect(()=>{alive.current=true;return()=>{alive.current=false;catalogId.current++;requestId.current++;bridge.current?.close()}},[]);
const agent=getAgent(s.agent);
const chooseAgent=(id:string)=>{const next=getAgent(id);s.setAgent(next.id);if(mode==='demo')s.setModel(next.model);setStage(0);setFlowOutputs([]);setError('')};
const startAgent=(id:string)=>{chooseAgent(id);if(!s.prompt.trim())s.setPrompt(getAgent(id).example);switchView('compose');requestAnimationFrame(()=>textarea.current?.focus())};
const selectedModel=models.find(x=>x.id===s.model);const basePayload=buildPayload(s.model,s.prompt,s.items,s.selected,s.turns,s.selectedTurns,mode==='external'?selectedModel?.provider:undefined);
const stages=flow==='compare'?['Model A','Model B']:['Generate','Critique','Refine'];const isWorkflow=tab==='workflows';const flowPrompt=flow!=='compare'&&stage>0?`${stage===1?'Critique':'Refine'} the following draft in relation to this request:\n${s.prompt}\n\nDraft:\n${flowOutputs.at(-1)?.content||''}`:s.prompt;const stageModel=flow==='compare'&&stage===1?second:s.model;const rawPayload=isWorkflow?buildPayload(stageModel,flowPrompt,s.items,s.selected,[],[],mode==='external'?models.find(x=>x.id===stageModel)?.provider:undefined):basePayload;const payload=withAgent(rawPayload,s.agent);const key=JSON.stringify({mode,payload,tab,stage,flow});const reviewed=review?.key===key;const approved=hasReviewApproval(review,key);
useEffect(()=>{setReview(null);setReviewOpen(false);setExampleResult(null)},[key]);
const workedExample=homeRequests.find(example=>matchesWorkedRequest(payload,withAgent(buildPayload(example.model,example.prompt,example.context,example.context.slice(0,2).map(item=>item.id),[],[]),requestAgent(example))));const showExampleResult=exampleResult?.key===key&&!isWorkflow;
useEffect(()=>{const registry=(document as any).modelContext;if(!registry?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(registry.registerTool({name:'stage_anonyx_prompt',title:'Stage an Anonyx prompt',description:'Set the visible draft for review. Does not send or run a request.',inputSchema:{type:'object',properties:{prompt:{type:'string',maxLength:10000}},required:['prompt'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const value=input as {prompt?:unknown};if(!value||typeof value.prompt!=='string'||value.prompt.length>10000)throw Error('Prompt must be text up to 10,000 characters.');s.setPrompt(value.prompt);setReview(null);setTab('compose');return{status:'staged',sent:false}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[s.setPrompt]);
const enableLive=async()=>{const id=++catalogId.current;setCatalogLoading(true);setError('');try{bridge.current?.close();bridge.current=new InferenceBridge().open();const catalog=await bridge.current.request<LiveModel[]>('catalog');if(!alive.current||id!==catalogId.current)return;if(!Array.isArray(catalog)||catalog.some(x=>!x.id||!x.provider))throw Error('The AI connection could not be checked.');setModels(catalog);if(catalog.length){setMode('external');s.setModel(catalog[0].id);setSecond(catalog[1]?.id||catalog[0].id)}else{setMode('demo');s.setModel(getAgent(s.agent).model)}setStage(0);setFlowOutputs([])}catch(e){if(alive.current&&id===catalogId.current)setError((e as Error).message)}finally{if(alive.current&&id===catalogId.current)setCatalogLoading(false)}};
useEffect(()=>{void enableLive()},[]);
const run=async()=>{if(!hasReviewApproval(review,key)||!s.prompt.trim()||busy)return;if(mode==='demo'){setReviewOpen(false);if(workedExample&&!isWorkflow)setExampleResult({id:workedExample.id,key});setAction(isWorkflow?'Workflow execution':agent.name);return}const confirmed=review!.payload;const capture=s.epoch.current;const id=++requestId.current;setBusy(true);setError('');try{if(mode==='external'&&(!models.some(x=>x.id===confirmed.model)||!bridge.current))throw Error('Choose a model from a current live catalog.');const text=await bridge.current!.request<string>('chat',confirmed);if(capture!==s.epoch.current||id!==requestId.current||!alive.current)return;if(typeof text!=='string')throw Error('The provider returned an unsupported response.');const response:Turn={id:newId(),role:'assistant',content:text,model:confirmed.model,mode};if(isWorkflow){setFlowOutputs(prev=>[...prev,response]);setStage(prev=>prev+1)}else{s.setTurns(prev=>[...prev,{id:newId(),role:'user',content:s.prompt,model:confirmed.model,mode},response]);if(currentDraft.current===s.prompt)s.setPrompt('')}setReview(null);setReviewOpen(false)}catch(e){if(id===requestId.current&&alive.current){setError((e as Error).message);if(e instanceof InferenceError&&e.code==='sign_in_required')setDisclosure(true)}}finally{if(id===requestId.current&&alive.current)setBusy(false)}};
const stop=()=>{bridge.current?.close();requestId.current++;setBusy(false);setReview(null);setError('Stopped. Any late response will be ignored. A provider may still finish and charge for a request already sent.')};
const end=()=>{bridge.current?.close();requestId.current++;s.endSession();setBusy(false);setReview(null);setFlowOutputs([]);setStage(0);setOriginal(null);setError('');toast.success(s.persist?'Draft, history, and selections cleared. Saved context remains on this device.':'Draft, history, and selections cleared. You can manage remaining context in the Context tab.')};
const modelOptions=mode==='demo'?demoModels:models.map(m=>({value:m.id,label:`${m.name} · ${m.provider}`}));const selectedCount=s.items.filter(item=>s.selected.includes(item.id)).length;
const historyCount=s.turns.filter(turn=>s.selectedTurns.includes(turn.id)).length;
const currentModel=modelOptions.find(model=>model.value===(isWorkflow?stageModel:s.model))?.label||s.model;
const switchView=(value:string)=>{if(busy)stop();setTab(value);setSidebarOpen(false)};
const resetSession=()=>{end();setTab('compose');setResetOpen(false);setSidebarOpen(false);setContextOpen(false);setReviewOpen(false);requestAnimationFrame(()=>textarea.current?.focus())};
const newSession=()=>{setResetIntent('new');if(s.prompt||s.turns.length||s.selected.length||flowOutputs.length)setResetOpen(true);else resetSession()};
const openReview=()=>{if(!s.prompt.trim()||busy||(isWorkflow&&stage>=stages.length))return;setReview(createRequestReview(key,payload));setReviewOpen(true)};
const submit=()=>{if(approved){setReviewOpen(true);return}openReview()};
const starters=homeRequests.filter(request=>['client-brief','bug-diagnosis','research-summary','study-plan'].includes(request.id));
const loadExample=(example:HomeRequest)=>{const items=[...s.items];const ids=example.context.map(item=>{const existing=items.find(saved=>saved.title===item.title&&saved.body===item.body);if(existing)return existing.id;const added={...item,id:newId()};items.push(added);return added.id});if(!s.saveItems(items)){setError('The example context could not be loaded. Your draft is preserved.');return}chooseAgent(requestAgent(example));s.setPrompt(example.prompt);s.setSelected([]);s.setSelectedTurns([]);switchView('compose');setOriginal(null);requestAnimationFrame(()=>textarea.current?.focus());return ids};
const suggestedExample=homeRequests.find(example=>example.prompt===s.prompt&&requestAgent(example)===s.agent);
const selectSuggestedContext=()=>{if(!suggestedExample)return;const ids=suggestedExample.context.slice(0,2).map(item=>s.items.find(saved=>saved.title===item.title&&saved.body===item.body)?.id);if(ids.some(id=>!id)){toast.info('Load the example from AI agents before selecting its context.');return}s.setSelected(ids as string[]);s.setSelectedTurns([])};
useEffect(()=>{const keyboard=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();newSession()}if(event.key==='Escape')setSidebarOpen(false)};window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard)},[s.prompt,s.turns.length,s.selected.length,flowOutputs.length]);
useEffect(()=>{if(!textarea.current)return;textarea.current.style.height='auto';textarea.current.style.height=Math.min(textarea.current.scrollHeight,180)+'px'},[s.prompt,tab]);
useEffect(()=>{const media=matchMedia('(max-width:850px)');const update=()=>{setSmallScreen(media.matches);if(!media.matches)setSidebarOpen(false)};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
useEffect(()=>{if(sidebarOpen&&smallScreen)requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.workspace-new-session')?.focus());else if(wasSidebarOpen.current&&smallScreen)menuButton.current?.focus();wasSidebarOpen.current=sidebarOpen},[sidebarOpen,smallScreen]);
const selectStarter=(starter:HomeRequest)=>{loadExample(starter)};
const contextChoices=<><p className="workspace-dialog-intro">Select only the context this request needs. Items stay excluded until you choose them.</p><div className="field"><label htmlFor="context-filter">Find context</label><input id="context-filter" placeholder="Search titles or tags" value={inputSearch} onChange={event=>setInputSearch(event.target.value)}/></div>{s.items.length?s.items.filter(item=>(item.title+' '+item.tags.join(' ')).toLowerCase().includes(inputSearch.toLowerCase())).map(item=><div className="context-choice" key={item.id}><Checkbox id={'select-'+item.id} checked={s.selected.includes(item.id)} onCheckedChange={value=>s.setSelected(value===true?[...s.selected,item.id]:s.selected.filter(id=>id!==item.id))}/><label htmlFor={'select-'+item.id}>{item.title}<small>{item.type} · {item.body.length} characters</small></label></div>):<div className="workspace-context-empty"><Layers3 size={25}/><p>Your library starts empty. Add useful details in Context, or send a request without them.</p></div>}<button className="button secondary small" onClick={()=>{setContextOpen(false);switchView('context')}}><Plus size={15}/>Manage context</button>{s.turns.length>0&&<><h3 className="workspace-history-label">Conversation turns</h3><p className="workspace-dialog-intro">Previous messages are excluded unless selected.</p>{s.turns.map((turn,index)=><div className="context-choice" key={turn.id}><Checkbox id={'history-'+turn.id} checked={s.selectedTurns.includes(turn.id)} onCheckedChange={value=>s.setSelectedTurns(value===true?[...s.selectedTurns,turn.id]:s.selectedTurns.filter(id=>id!==turn.id))}/><label htmlFor={'history-'+turn.id}>{index+1}. {turn.role==='user'?'You':'Response'}<small>{turn.content.slice(0,90)}{turn.content.length>90?'…':''}</small></label></div>)}</>}{s.items.length>0&&inputSearch&&!s.items.some(item=>(item.title+' '+item.tags.join(' ')).toLowerCase().includes(inputSearch.toLowerCase()))&&<p className="workspace-dialog-intro">No context matches this search.</p>}</>;
return <div className={'app-workspace calm-workspace'+(sidebarOpen?' sidebar-open':'')}>
  {sidebarOpen&&<button className="workspace-sidebar-backdrop" aria-label="Close workspace menu" onClick={()=>setSidebarOpen(false)}/>}
  <aside className="workspace-nav" aria-label="Workspace navigation" inert={smallScreen&&!sidebarOpen} aria-hidden={smallScreen&&!sidebarOpen?true:undefined}>
    <div className="workspace-brand-row"><a href="/" className="brand"><Mark/><span>anonyx</span></a><button className="workspace-icon-button mobile-only" aria-label="Close workspace menu" onClick={()=>setSidebarOpen(false)}><X size={20}/></button></div>
    <button className="workspace-new-session" onClick={newSession}><Plus size={18}/><span>New session</span><kbd>Ctrl K</kbd></button>
    <nav className="workspace-primary-nav" aria-label="Workspace tools">{[{id:'compose',name:'Chat',Icon:MessageSquare},{id:'agents',name:'AI agents',Icon:ShieldCheck},{id:'context',name:'Context library',Icon:Layers3},{id:'workflows',name:'Workflows',Icon:Workflow}].map(({id,name,Icon})=><button key={id} className={tab===id?'active':''} onClick={()=>switchView(id)} aria-current={tab===id?'page':undefined}><Icon size={18}/><span>{name}</span>{id==='context'&&<small>{s.items.length}</small>}</button>)}</nav>
    <div className="workspace-session-list"><div className="workspace-nav-label"><span>THIS CHAT</span><span>{String(s.turns.filter(turn=>turn.role==='user').length).padStart(2,'0')}</span></div>{s.turns.filter(turn=>turn.role==='user').length?s.turns.filter(turn=>turn.role==='user').map(turn=><button key={turn.id} className="workspace-session-item" onClick={()=>{switchView('compose');requestAnimationFrame(()=>document.getElementById('turn-'+turn.id)?.scrollIntoView({block:'start'}))}}><MessageSquare size={14}/><span>{turn.content.slice(0,65)}</span></button>):<p>No messages yet</p>}</div>
    <div className="workspace-nav-bottom"><button className="workspace-plain-link" onClick={()=>{setPrivacyOpen(true);setSidebarOpen(false)}}><ShieldCheck size={17}/>Privacy controls</button><button className="workspace-plain-link" onClick={()=>{setDisclosure(true);setSidebarOpen(false)}}><Code2 size={17}/>AI connection</button><details className="workspace-resources"><summary>Resources</summary><nav aria-label="Anonyx links"><a href="/developers">Developers</a><a href="/tokenomics">Tokenomics</a><a href="/whitepaper">Whitepaper</a><a href="/privacy">Privacy</a><a href={GITHUB_URL} target="_blank" rel="noopener noreferrer">GitHub</a><a href={X_URL} target="_blank" rel="noopener noreferrer">Connect to X</a></nav></details><a className="workspace-plain-link" href="/"><Home size={17}/>Back to website</a></div>
  </aside>
  <div className="workspace-surface" inert={smallScreen&&sidebarOpen}>
    <header className="workspace-app-header"><div className="workspace-header-title"><button ref={menuButton} className="workspace-icon-button mobile-only" aria-label="Open workspace menu" aria-expanded={sidebarOpen} onClick={()=>setSidebarOpen(true)}><Menu size={20}/></button><span>{tab==='agents'?'AI agents':tab==='context'?'Context library':tab==='workflows'?'Workflows':'New chat'}</span></div><div className="workspace-header-actions"><button className="workspace-local-status" onClick={()=>setPrivacyOpen(true)}><LockKeyhole size={14}/><span>{mode==='external'?selectedModel?.provider||'AI connected':'Privacy controls'}</span></button><button className="button secondary small" onClick={openWallet}><Wallet size={16}/><span>Connect Wallet</span></button></div></header>
    <div className="workspace-main-scroll" id="workspace-scroll">
      {tab==='agents'?<section className="workspace-agents-view"><div className="workspace-view-title"><span className="eyebrow">YOUR TASK. YOUR AGENT.</span><h1>Choose your agent.</h1><p>A useful focus for each task.</p></div><AgentOptions value={s.agent} onChange={chooseAgent}/><div className="agent-detail"><span className="eyebrow">{agent.role}</span><h2>{agent.name}</h2><p>{agent.description}</p><details><summary>View agent instructions</summary><p>{agent.instruction}</p></details><div className="button-row"><button className="button primary" onClick={()=>startAgent(agent.id)}>Use {agent.name}</button><button className="button secondary" onClick={()=>loadExample(homeRequests.find(request=>requestAgent(request)===agent.id)||homeRequests[0])}>Load example request</button><a className="text-link" href="/walkthrough">Explore all 10 requests</a></div></div></section>:tab==='context'?<div className="workspace-library-view"><div className="workspace-view-title"><span className="eyebrow">YOUR CONTEXT, BY CHOICE</span><h1>Your context library.</h1><p>Add details to use when you need them.</p></div><ContextManager/></div>:<div className={'workspace-conversation '+(isWorkflow?'workflow-view':'')}>

        {isWorkflow?<section className="workspace-workflow"><div className="workspace-view-title"><span className="eyebrow">MULTI-MODEL WORKFLOWS</span><h1>Work, step by step.</h1><p>You review and approve every stage.</p></div><div className="workspace-workflow-options"><Picker label="Workflow" value={flow} onChange={value=>{setFlow(value);setStage(0);setFlowOutputs([])}} options={[{value:'compare',label:'Compare two models'},{value:'refine',label:'Generate · Critique · Refine'}]}/>{flow==='compare'&&<Picker label="Second model" value={second} onChange={value=>{setSecond(value);setStage(0);setFlowOutputs([])}} options={modelOptions}/>}</div><div className="flow-stages">{stages.map((name,index)=><div className="flow-stage" key={name}><span className={'badge '+(index===stage?'teal':'')}>{index<stage?'Complete':index===stage?'Current':'Waiting'}</span><strong>{name}</strong><p>{flow==='compare'?'A separate response to the same prompt.':index===0?'Create the first response.':index===1?'Review the first response.':'Refine the previous stage.'}</p></div>)}</div>{flowOutputs.map((output,index)=><article key={output.id} className="workspace-message assistant-message"><div className="workspace-message-heading"><Mark/><strong>{stages[index]}</strong><span>{modelOptions.find(model=>model.value===output.model)?.label||output.model}</span></div><p>{output.content}</p></article>)}{stage>=stages.length&&<button className="button secondary" onClick={()=>{setStage(0);setFlowOutputs([]);setReview(null)}}>Start a new workflow</button>}</section>:s.turns.length?<div className="workspace-transcript">{s.turns.map(turn=><article className={'workspace-message '+(turn.role==='user'?'user-message':'assistant-message')} key={turn.id} id={'turn-'+turn.id}><div className="workspace-message-heading">{turn.role==='assistant'&&<Mark/>}<strong>{turn.role==='user'?'You':'Anonyx'}</strong><span>{modelOptions.find(model=>model.value===turn.model)?.label||turn.model}</span></div><p>{turn.content}</p></article>)}</div>:showExampleResult?null:<section className="workspace-welcome"><div className="workspace-welcome-mark"><Mark/></div><h1>What’s on your mind?</h1><p>A little context. A better conversation.</p><div className="workspace-starters">{starters.map(starter=><button key={starter.id} onClick={()=>selectStarter(starter)}><Plus size={14}/><strong>{starter.title}</strong></button>)}</div></section>}
        {showExampleResult&&exampleResult&&<WorkedOutput requestId={exampleResult.id} id="workspace-example-result"/>}
      </div>}
      {error&&<div className="workspace-inline-error notice error" role="alert">{error}</div>}
    </div>
    {tab!=='context'&&tab!=='agents'&&<div className="workspace-composer-dock">{suggestedExample&&!isWorkflow&&<div className="workspace-example-context"><span>{suggestedExample.title} context</span><button className="button secondary small" onClick={selectSuggestedContext}>Use suggested context</button></div>}<div className="workspace-composer"><label className="sr-only" htmlFor="prompt">Your prompt</label><textarea ref={textarea} id="prompt" value={s.prompt} maxLength={10000} onChange={event=>{s.setPrompt(event.target.value);if(isWorkflow){setStage(0);setFlowOutputs([])}}} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();if(!busy)submit()}}} placeholder={isWorkflow?'What should this workflow work on?':'Message Anonyx…'} rows={2}/>{toolsOpen&&<div className="workspace-extra-tools"><div className="workspace-mask-tools"><button disabled={!s.prompt||busy} onClick={()=>{setOriginal(s.prompt);s.setPrompt(maskIdentifiers(s.prompt));toast.info('Common email and phone patterns masked. Check the text for anything missed.')}}><ScanLine size={14}/>Mask identifiers</button><button disabled={!s.prompt||busy} onClick={()=>{const input=textarea.current;if(!input||input.selectionStart===input.selectionEnd){toast.info('Select text in the prompt first.');return}setOriginal(s.prompt);s.setPrompt(s.prompt.slice(0,input.selectionStart)+'[MASKED]'+s.prompt.slice(input.selectionEnd))}}>Mask selection</button>{original!==null&&<button onClick={()=>{s.setPrompt(original);setOriginal(null)}}><Undo2 size={13}/>Undo</button>}<span>{s.prompt.length.toLocaleString()} / 10,000</span></div>{mode==='external'&&<Picker label="Model" value={s.model} onChange={s.setModel} options={modelOptions}/>}</div>}<div className="workspace-composer-controls"><div className="workspace-model-controls"><Picker label="Agent" value={s.agent} onChange={chooseAgent} options={agents.map(agent=>({value:agent.id,label:agent.name}))}/><button className="workspace-icon-button" onClick={()=>setToolsOpen(value=>!value)} aria-label="Prompt tools" aria-expanded={toolsOpen}><ScanLine size={17}/></button><button className="workspace-context-toggle" onClick={()=>setContextOpen(true)}><Layers3 size={15}/><span>Context</span><b>{selectedCount}</b></button></div><div className="workspace-submit-controls">{busy?<button className="button danger small" onClick={stop}><StopCircle size={16}/>Stop</button>:<button className="button primary small" disabled={!s.prompt.trim()||(isWorkflow&&stage>=stages.length)} onClick={submit}><Eye size={16}/>{approved?'Review approved':'Review & send'}</button>}</div></div></div><div className="workspace-dock-note"><span><LockKeyhole size={12}/>Only selected context is included</span><span>Shift+Enter for a new line</span></div></div>}
  </div>
  <Dialog open={contextOpen} onOpenChange={setContextOpen}><DialogContent className="workspace-context-dialog"><DialogTitle>Request context <span className="badge">{selectedCount} items · {isWorkflow?0:historyCount} turns</span></DialogTitle><DialogDescription>Your library stays separate from your request.</DialogDescription>{contextChoices}{isWorkflow&&<p className="workspace-dialog-intro">Selected conversation turns apply to the chat workspace. Each workflow stage uses its own reviewed prompt.</p>}</DialogContent></Dialog>
  <Dialog open={privacyOpen} onOpenChange={setPrivacyOpen}><DialogContent className="workspace-privacy-dialog"><DialogTitle>Your privacy controls</DialogTitle><DialogDescription>Know what stays on your device and what an approved request can share.</DialogDescription><PrivacyStatus/><p className="workspace-dialog-intro">Masking can miss identifying details. External providers can read submitted text and apply their own data-use policies. A local session does not guarantee anonymous or confidential inference.</p><div className="button-row"><a href="/privacy" className="button secondary small">Explore privacy</a><a href="/privacy-policy" className="button ghost small">Data handling policy</a></div></DialogContent></Dialog>
  <Dialog open={reviewOpen&&reviewed} onOpenChange={setReviewOpen}><DialogContent className="workspace-review-dialog"><DialogTitle>Review before you share</DialogTitle><DialogDescription>{agent.name} · {currentModel} · {isWorkflow?stages[stage]:'Current request'}</DialogDescription>{reviewed&&review&&<RequestReceipt payload={review.payload} external={mode==='external'} contextCount={selectedCount} historyCount={isWorkflow?0:historyCount} workflowInput={isWorkflow&&flow!=='compare'&&stage>0} sending={busy} approved={approved} onApproval={value=>setReview(current=>current?.key===key?{...current,approved:value}:null)}/>}<div className="workspace-review-actions"><button className="button secondary" onClick={()=>setReviewOpen(false)}>Back to draft</button><button className="button primary" disabled={!approved||busy} onClick={run}>{busy?'Sending…':isWorkflow?'Run workflow':'Run agent'}</button></div>{error&&<p className="error-text" role="alert">{error}</p>}</DialogContent></Dialog>
  <Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent><DialogTitle>{resetIntent==='new'?'Start a new session?':'End this session?'}</DialogTitle><DialogDescription>Clear this draft, transcript, selected context, and workflow outputs. Your context library remains available. Requests already sent may still be processed by their provider.</DialogDescription><div className="button-row"><button className="button secondary" onClick={()=>setResetOpen(false)}>Keep this session</button><button className="button primary" onClick={resetSession}>{resetIntent==='new'?'Start new session':'End Session'}</button></div></DialogContent></Dialog>
  <Dialog open={disclosure} onOpenChange={setDisclosure}><DialogContent><DialogTitle>AI connection</DialogTitle><DialogDescription>Provider access is managed by Anonyx. Your API key never belongs in this chat.</DialogDescription><p className="workspace-dialog-intro">{models.length?`${models[0].provider} · ${models[0].name}`:'Your workspace is ready for a server-managed AI connection.'}</p><p className="workspace-dialog-intro">Only a request you review and approve is sent. The provider’s retention and data-use policies apply.</p>{error&&<p className="error-text" role="alert">{error}</p>}<div className="button-row">{models.length&&<a className="button primary" href="/signin-with-chatgpt?return_to=%2Fworkspace" target="_top">Sign in for AI access</a>}<button className="button secondary" onClick={enableLive} disabled={catalogLoading||busy}>{catalogLoading?'Checking…':'Check connection'}</button><button className="button ghost" onClick={()=>setDisclosure(false)}>Close</button></div></DialogContent></Dialog>
  <ServiceNotice action={action} continueLabel={showExampleResult?'View example result':'Keep editing'} detail={action&&!workedExample&&!isWorkflow?'A fresh response needs live AI. Explore the prepared request examples from AI agents or the guided walkthrough. Your draft remains available.':undefined} onClose={()=>{setAction(null);if(showExampleResult)requestAnimationFrame(()=>document.getElementById('workspace-example-result')?.focus())}}/>
</div>;
}
